name: 'Terraform CI'

on:
  pull_request:
    branches:
      - master

env:
  TF_VERSION: 1.3.7

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup providers configuration
        shell: bash
        run: |
          cat << EOF > provider.tf
          provider "azurerm" {
            features {}
          }
          EOF
      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate